### ISSUE TITLE
Create a new Social Media Policy

### ISSUE THREAD

**Issue by HiraBZ** [WorldEnterpriseGroup/Reveltek-Careers#12]
**_Let’s create a new Social Media Policy_**

People can only have professional profiles where they articulate their real name, and their real photo, and use English.
They cannot have extremist photos 

Links for help: https://www.indeed.com/hire/c/info/social-media-policy
Some of the important points for Social Media Policy. All of this is normal in a Social Media Policy.
1. People can only have professional profiles where they articulate their real name, and their real photo, and use English.
2. They cannot have extremist photos up or affiliate with terrorist groups.
3. They must have accounts on:
LinkedIn
Facebook
MS Team's 
4. They cannot list that they work for any other company but ours while full-time employed with us.
5. They must make sure to take responsibility for our reputation in their social media posts.
6. They cannot bully others online.
7. They cannot attend riots or destructive social gatherings.
8. How they conduct themselves in public and on social media is a reflection of our firm and our values.
9. Applicants who are or plan to be quiet, shy, introverted, hide, poor social skills, no social profiles, no professional clothing, no photos are not at all welcomed in the company. 
10. We want videos when in calls. 
11. Low audio volume when in calls or just do not respond at all is not what we are accepting at all.

**Comment by HiraBZ** [comment]
@Ftkhan717

**Comment by Ftkhan717** [comment]
@HiraBZ, Please check out the above details about Social Media Policy.

**Comment by HiraBZ** [comment]
Fajar, I had to make it again. You tried to copy paste a lot from the bots or AI.
